/* eslint-disable func-style */
/* eslint-disable max-len */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        UNOCORE_CATEGORY: 'UnoCore',
        UNOCORE_INIT: 'init UnoCore',
        UNOCORE_SETSERVODEGREE: 'set servo %1 degree %2',
        UNOCORE_SETMOTORSPEED: 'set motor %1 direction %2 speed %3',
        UNOCORE_FORWARD: 'forward',
        UNOCORE_BACKWARD: 'backward',
        UNOCORE_STOPMOTOR: 'break motor %1',
        UNOCORE_SETRGBLEDCOLOR: 'set RGB LED %1 color %2',
        UNOCORE_ALL: 'all',
        UNOCORE_LEFT: 'left',
        UNOCORE_RIGHT: 'right',
        UNOCORE_SETBUZZER: 'Buzzer play %1',
        UNOCORE_SOUND_CONNECT: 'connect',
        UNOCORE_SOUND_DISCONNECT: 'disconnect',
        UNOCORE_SOUND_BUTTON: 'button',
        UNOCORE_SOUND_MODE: 'mode',
        UNOCORE_SOUND_SUPERRISE: 'superrise',
        UNOCORE_SOUND_OHOH: 'ohoh',
        UNOCORE_SOUND_OHOH2: 'ohoh2',
        UNOCORE_SOUND_CUTE: 'cute',
        UNOCORE_SOUND_HAPPY: 'happy',
        UNOCORE_SOUND_SAD: 'sad',
        UNOCORE_SOUND_SAD2: 'sad2',
        UNOCORE_PS2READDATA: 'PS2 read data',
        UNOCORE_PS2GETBUTTON: 'PS2 %1 button is pressed?',
        UNOCORE_PS2_UP: 'up',
        UNOCORE_PS2_DOWN: 'down',
        UNOCORE_PS2_LEFT: 'left',
        UNOCORE_PS2_RIGHT: 'right',
        UNOCORE_PS2_TRIANGLE: 'triangle',
        UNOCORE_PS2_CIRCLE: 'circle',
        UNOCORE_PS2_CROSS: 'cross',
        UNOCORE_PS2_SQUARE: 'square',
        UNOCORE_PS2_SELECT: 'select',
        UNOCORE_PS2_START: 'start',
        UNOCORE_PS2GETJOYSTICK: 'PS2 get joystick %1',
        UNOCORE_RGBULTRASONICINIT: 'RGB ultrasonic init data pin %1 RGB pin %2',
        UNOCORE_RGBULTRASONICSETCOLORSTYLE: 'set rgb ultrasonic %1 LED color %2 style %3',
        UNOCORE_NONE: 'none',
        UNOCORE_BREATHING: 'breathing',
        UNOCORE_ROTATE: 'rotate',
        UNOCORE_FLASH: 'flash',
        UNOCORE_RGBULTRASONICREADDISTANCE: 'rgb ultrasonic read distance'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        UNOCORE_CATEGORY: '工程车套件',
        UNOCORE_INIT: '初始化工程车套件',
        UNOCORE_SETSERVODEGREE: '设置舵机 %1 角度 %2',
        UNOCORE_SETMOTORSPEED: '设置电机 %1 方向 %2 速度 %3',
        UNOCORE_FORWARD: '正转',
        UNOCORE_BACKWARD: '倒转',
        UNOCORE_STOPMOTOR: '电机 %1 刹车',
        UNOCORE_SETRGBLEDCOLOR: '设置RGB LED %1 颜色为 %2',
        UNOCORE_ALL: '全部',
        UNOCORE_LEFT: '左边',
        UNOCORE_RIGHT: '右边',
        UNOCORE_SETBUZZER: '蜂鸣器播放 %1',
        UNOCORE_SOUND_CONNECT: '连接',
        UNOCORE_SOUND_DISCONNECT: '断开连接',
        UNOCORE_SOUND_BUTTON: '按键',
        UNOCORE_SOUND_MODE: '模式',
        UNOCORE_SOUND_SUPERRISE: '惊讶',
        UNOCORE_SOUND_OHOH: '哦哦',
        UNOCORE_SOUND_OHOH2: '哦哦2',
        UNOCORE_SOUND_CUTE: '可爱',
        UNOCORE_SOUND_HAPPY: '开心',
        UNOCORE_SOUND_SAD: '伤心',
        UNOCORE_SOUND_SAD2: '伤心2',
        UNOCORE_PS2READDATA: 'PS2读取数据',
        UNOCORE_PS2GETBUTTON: 'PS2 %1 按键被按下?',
        UNOCORE_PS2_UP: '上',
        UNOCORE_PS2_DOWN: '下',
        UNOCORE_PS2_LEFT: '左',
        UNOCORE_PS2_RIGHT: '右',
        UNOCORE_PS2_TRIANGLE: '三角',
        UNOCORE_PS2_CIRCLE: '圆',
        UNOCORE_PS2_CROSS: '叉号',
        UNOCORE_PS2_SQUARE: '方块',
        UNOCORE_PS2_SELECT: '选择',
        UNOCORE_PS2_START: '开始',
        UNOCORE_PS2GETJOYSTICK: 'PS2获取摇杆 %1',
        UNOCORE_RGBULTRASONICINIT: 'RGB超声波传感器初始化 数据引脚 %1 RGB引脚 %2',
        UNOCORE_RGBULTRASONICSETCOLORSTYLE: '设置RGB超声波传感器 %1 LED颜色 %2 样式 %3',
        UNOCORE_NONE: '无',
        UNOCORE_BREATHING: '呼吸',
        UNOCORE_ROTATE: '旋转',
        UNOCORE_FLASH: '闪烁',
        UNOCORE_RGBULTRASONICREADDISTANCE: 'RGB超声波传感器读取距离'
    });
    return Blockly;
}

exports = addMsg;
